namespace EmberConfig.PrefabDataGen.Generation;

using System.Collections.Generic;
using System.Text;

internal static class CSharpCodeBuilder
{
    private static readonly IReadOnlyList<string> DefaultUsings = new[]
    {
        "TMPro",
        "UnityEngine",
        "UnityEngine.UI",
        "EmberConfig.UI"
    };

    internal static void AppendFileHeader(StringBuilder sb, string className, IReadOnlyList<string> summaryLines)
    {
        AppendFileHeader(sb, className, summaryLines, DefaultUsings);
    }

    internal static void AppendFileHeader(
        StringBuilder sb,
        string className,
        IReadOnlyList<string> summaryLines,
        IReadOnlyList<string> usings)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();

        foreach (var u in usings)
            sb.AppendLine($"using {u};");

        sb.AppendLine();
        sb.AppendLine("/// <summary>");

        foreach (var line in summaryLines)
            sb.AppendLine($"/// {line}");

        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class {className}");
        sb.AppendLine("{");
    }

    internal static void AppendMethodStart(StringBuilder sb, string returnType, string parameters)
    {
        sb.AppendLine($"    internal static {returnType} Create({parameters})");
        sb.AppendLine("    {");
    }

    internal static void AppendMethodEnd(StringBuilder sb)
    {
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    internal static void AppendRecordConstructor(
        StringBuilder sb,
        string? returnVariable,
        string typeName,
        IReadOnlyList<string> arguments,
        IReadOnlyList<string>? initializerLines = null)
    {
        var prefix = returnVariable is null ? "return" : $"var {returnVariable} =";
        sb.AppendLine($"        {prefix} new {typeName}(");

        for (var i = 0; i < arguments.Count; i++)
        {
            var isLast = i == arguments.Count - 1;

            if (isLast && (initializerLines is null || initializerLines.Count == 0))
            {
                sb.AppendLine($"            {arguments[i]});");
            }
            else if (isLast)
            {
                sb.AppendLine($"            {arguments[i]})");
            }
            else
            {
                sb.AppendLine($"            {arguments[i]},");
            }
        }

        if (initializerLines is not null && initializerLines.Count > 0)
        {
            sb.AppendLine("        {");

            foreach (var line in initializerLines)
                sb.AppendLine(line);

            sb.AppendLine("        };");
        }
    }
}
