namespace EmberConfig.PrefabDataGen.Generation;

using System;
using System.Globalization;
using System.IO;
using System.Text;
using EmberConfig.PrefabDataGen.Models;

internal static class CSharpFileWriter
{
    internal static void WriteRowRawStyle(string outputPath, RowRawStyle style)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated raw row style. Runtime assets are stored as names and resolved by the factory.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed record RowRawStyle(");
        sb.AppendLine($"    ExtractedTextAppearance TitleText,");
        sb.AppendLine($"    string? BackgroundSpriteName,");
        sb.AppendLine($"    Color BackgroundColor,");
        sb.AppendLine($"    Color HighlightColor,");
        sb.AppendLine($"    Image.Type BackgroundType,");
        sb.AppendLine($"    float Height,");
        sb.AppendLine($"    float Width,");
        sb.AppendLine($"    float TitleWidth,");
        sb.AppendLine($"    float ItemWidth,");
        sb.AppendLine($"    RectData RowRect,");
        sb.AppendLine($"    RectData TitleRect,");
        sb.AppendLine($"    RectData ItemRect);");
        sb.AppendLine();

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    internal static void WriteStyleFactory(string outputPath, RowRawStyle style)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated factory that turns raw prefab data into runtime style records.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class PrefabStyleFactory");
        sb.AppendLine("{");
        sb.AppendLine("    internal static StyleCatalog Create(TextMeshProUGUI? descriptionText)");
        sb.AppendLine("    {");
        sb.AppendLine("        var row = CreateRowStyle(descriptionText);");
        sb.AppendLine("        return new StyleCatalog(row, null, GroupHeaderStyle.Default(row.Title), null, null, null, null, null, null);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static RowStyle CreateRowStyle(TextMeshProUGUI? descriptionText)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var title = {TextAppearanceLiteral(style.TitleText)};");
        sb.AppendLine($"        return new RowStyle(");
        sb.AppendLine($"            title,");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(style.BackgroundSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(style.BackgroundColor)},");
        sb.AppendLine($"            {ColorLiteral(style.HighlightColor)},");
        sb.AppendLine($"            (Image.Type){style.BackgroundType},");
        sb.AppendLine($"            {Float(style.Height)}f,");
        sb.AppendLine($"            {Float(style.Width)}f,");
        sb.AppendLine($"            {Float(style.TitleWidth)}f,");
        sb.AppendLine($"            {Float(style.ItemWidth)}f,");
        sb.AppendLine($"            descriptionText,");
        sb.AppendLine($"            {RectDataLiteral(style.RowRect)},");
        sb.AppendLine($"            {RectDataLiteral(style.TitleRect)},");
        sb.AppendLine($"            {RectDataLiteral(style.ItemRect)});");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    private static string ColorLiteral(Color color) =>
        $"new Color({Float(color.R)}f, {Float(color.G)}f, {Float(color.B)}f, {Float(color.A)}f)";

    private static string RectDataLiteral(RectData rect) =>
        $"new RectData(new Vector2({Float(rect.AnchorMinX)}f, {Float(rect.AnchorMinY)}f), new Vector2({Float(rect.AnchorMaxX)}f, {Float(rect.AnchorMaxY)}f), new Vector2({Float(rect.SizeDeltaX)}f, {Float(rect.SizeDeltaY)}f), new Vector2({Float(rect.AnchoredPositionX)}f, {Float(rect.AnchoredPositionY)}f), new Vector2({Float(rect.PivotX)}f, {Float(rect.PivotY)}f))";

    private static string TextAppearanceLiteral(ExtractedTextAppearance text) =>
        $"new TextAppearance(TMP_FontAssetResolver.Resolve({StringLiteral(text.FontAssetName)}), MaterialResolver.Resolve({StringLiteral(text.MaterialName)}), {Float(text.FontSize)}f, {ColorLiteral(text.Color)}, (TextAlignmentOptions){text.Alignment}, (FontStyles){text.FontStyle}, {Float(text.OutlineWidth)}f, {Bool(text.EnableWordWrapping)}, {Bool(text.EnableAutoSizing)}, (TextOverflowModes){text.OverflowMode}, {Float(text.FontSizeMin)}f, {Float(text.FontSizeMax)}f)";

    private static string StringLiteral(string? value) =>
        value is null ? "null" : $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Float(float value) =>
        value.ToString(CultureInfo.InvariantCulture);
}
