namespace EmberConfig.PrefabDataGen.Generation;

using System;
using System.Globalization;
using System.IO;
using System.Text;
using EmberConfig.PrefabDataGen.Models;

internal static class CSharpFileWriter
{
    internal static void WriteRowStyleFactory(string outputPath, RowRawStyle row)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated factory that creates the runtime RowStyle from raw prefab data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class RowStyleFactory");
        sb.AppendLine("{");
        sb.AppendLine("    internal static RowStyle Create(TextMeshProUGUI? descriptionText)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var title = {TextAppearanceLiteral(row.TitleText)};");
        sb.AppendLine($"        return new RowStyle(");
        sb.AppendLine($"            title,");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(row.BackgroundSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(row.BackgroundColor)},");
        sb.AppendLine($"            {ColorLiteral(row.HighlightColor)},");
        sb.AppendLine($"            (Image.Type){row.BackgroundType},");
        sb.AppendLine($"            {Float(row.Height)}f,");
        sb.AppendLine($"            {Float(row.Width)}f,");
        sb.AppendLine($"            {Float(row.TitleWidth)}f,");
        sb.AppendLine($"            {Float(row.ItemWidth)}f,");
        sb.AppendLine($"            descriptionText,");
        sb.AppendLine($"            {RectDataLiteral(row.RowRect)},");
        sb.AppendLine($"            {RectDataLiteral(row.TitleRect)},");
        sb.AppendLine($"            {RectDataLiteral(row.ItemRect)});");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    internal static void WriteDropdownStyleFactory(string outputPath, DropdownRawStyle dropdown)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated factory that creates the runtime DropdownStyle from raw prefab data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class DropdownStyleFactory");
        sb.AppendLine("{");
        sb.AppendLine("    internal static DropdownStyle Create(TextAppearance fallbackText)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var itemLabel = {TextAppearanceLiteral(dropdown.Item.LabelText)};");
        sb.AppendLine($"        var listItemLabel = {TextAppearanceLiteral(dropdown.Template.ItemLabelText)};");
        sb.AppendLine($"        var item = new DropdownItemStyle(");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Item.ItemSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Item.ItemColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Item.ItemType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Item.ItemRect)},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Item.LabelRect)},");
        sb.AppendLine($"            itemLabel,");
        sb.AppendLine($"            (TextAlignmentOptions){dropdown.Item.LabelAlignment},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Item.ArrowRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Item.ArrowSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Item.ArrowColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Item.ArrowType},");
        sb.AppendLine($"            {dropdown.Item.ControllerKey});");
        sb.AppendLine($"        var template = new DropdownTemplateStyle(");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.TemplateRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Template.TemplateSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Template.TemplateBgColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Template.TemplateImageType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.ViewportRect)},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.ContentRect)},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.TemplateItemRect)},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.TemplateHighlightRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Template.TemplateHighlightSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Template.TemplateHighlightColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Template.TemplateHighlightType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.ItemBackgroundRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Template.ItemBgSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Template.ItemBgColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Template.ItemBgType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.ItemCheckmarkRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Template.ItemCheckmarkSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Template.ItemCheckmarkColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Template.ItemCheckmarkType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Template.ItemLabelRect)},");
        sb.AppendLine($"            listItemLabel,");
        sb.AppendLine($"            (TextAlignmentOptions){dropdown.Template.ItemLabelAlignment},");
        sb.AppendLine($"            {dropdown.Template.CtrlBackKey})");
        if (dropdown.Template.ItemColorBlock is not null)
        {
            var cb = dropdown.Template.ItemColorBlock;
            sb.AppendLine($"        {{");
            sb.AppendLine($"            ItemColorBlock = new ColorBlock");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                normalColor = {ColorLiteral(cb.NormalColor)},");
            sb.AppendLine($"                highlightedColor = {ColorLiteral(cb.HighlightedColor)},");
            sb.AppendLine($"                pressedColor = {ColorLiteral(cb.PressedColor)},");
            sb.AppendLine($"                disabledColor = {ColorLiteral(cb.DisabledColor)},");
            sb.AppendLine($"                colorMultiplier = {Float(cb.ColorMultiplier)}f,");
            sb.AppendLine($"                fadeDuration = {Float(cb.FadeDuration)}f");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }};");
        }
        else
        {
            sb.AppendLine($"        ;");
        }
        sb.AppendLine($"        var scrollbar = new DropdownScrollbarStyle(");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Scrollbar.ScrollbarRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Scrollbar.ScrollbarSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Scrollbar.ScrollbarColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Scrollbar.ScrollbarType},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Scrollbar.SlidingAreaRect)},");
        sb.AppendLine($"            {RectDataLiteral(dropdown.Scrollbar.HandleRect)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(dropdown.Scrollbar.HandleSpriteName)}),");
        sb.AppendLine($"            {ColorLiteral(dropdown.Scrollbar.HandleColor)},");
        sb.AppendLine($"            (Image.Type){dropdown.Scrollbar.HandleType});");
        sb.AppendLine($"        return new DropdownStyle(item, template, scrollbar);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    internal static void WriteSwitchStyleFactory(string outputPath, SwitchRawStyle raw)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated factory that creates the runtime SwitchStyle from raw prefab data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class SwitchStyleFactory");
        sb.AppendLine("{");
        sb.AppendLine("    internal static SwitchStyle Create(TextAppearance fallbackText)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var labelText = {TextAppearanceLiteral(raw.Option.LabelText)};");
        sb.AppendLine($"        var clickGroupLayout = {SwitchLayoutGroupLiteral(raw.ClickGroupLayout)};");
        sb.AppendLine($"        var optionColorBlock = {ColorBlockLiteral(raw.Option.OptionColorBlock)};");
        sb.AppendLine($"        return new SwitchStyle(");
        sb.AppendLine($"            {ColorLiteral(raw.Option.BackgroundColor)},");
        sb.AppendLine($"            {ColorLiteral(raw.Option.CheckmarkColor)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(raw.Option.BackgroundSpriteName)}),");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(raw.Option.CheckmarkSpriteName)}),");
        sb.AppendLine($"            (Image.Type){raw.Option.BackgroundType},");
        sb.AppendLine($"            (Image.Type){raw.Option.CheckmarkType},");
        sb.AppendLine($"            labelText,");
        sb.AppendLine($"            {RectDataLiteral(raw.ClickGroupRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.Option.OptionRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.Option.LabelRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.Option.BackgroundRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.Option.CheckmarkRect)},");
        sb.AppendLine($"            clickGroupLayout,");
        sb.AppendLine($"            optionColorBlock,");
        sb.AppendLine($"            (Selectable.Transition){raw.Option.Transition},");
        sb.AppendLine($"            {Bool(raw.AllowSwitchOff)},");
        sb.AppendLine($"            {raw.ClickSoundEventId}u);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    internal static void WriteSliderStyleFactory(string outputPath, SliderRawStyle raw)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EmberConfig.Generated.PrefabData;");
        sb.AppendLine();
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using EmberConfig.UI;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated factory that creates the runtime SliderStyle from raw prefab data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class SliderStyleFactory");
        sb.AppendLine("{");
        sb.AppendLine("    internal static SliderStyle Create(TextAppearance fallbackText)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var numText = {TextAppearanceLiteral(raw.NumText)};");
        sb.AppendLine($"        var sliderColorBlock = {ColorBlockLiteral(raw.SliderColorBlock)};");
        sb.AppendLine($"        return new SliderStyle(");
        sb.AppendLine($"            {ColorLiteral(raw.BackgroundColor)},");
        sb.AppendLine($"            {ColorLiteral(raw.BgColor)},");
        sb.AppendLine($"            {ColorLiteral(raw.FillColor)},");
        sb.AppendLine($"            {ColorLiteral(raw.HandleColor)},");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(raw.BackgroundSpriteName)}),");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(raw.FillSpriteName)}),");
        sb.AppendLine($"            SpriteResolver.Resolve({StringLiteral(raw.HandleSpriteName)}),");
        sb.AppendLine($"            (Image.Type){raw.FillImageType},");
        sb.AppendLine($"            (Image.FillMethod){raw.FillFillMethod},");
        sb.AppendLine($"            {RectDataLiteral(raw.SliderPcUnitRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.SliderRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.BackgroundRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.BgRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.FillAreaRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.FillRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.HandleSlideAreaRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.HandleRect)},");
        sb.AppendLine($"            {RectDataLiteral(raw.NumRect)},");
        sb.AppendLine($"            numText,");
        sb.AppendLine($"            {Float(raw.Spacing)}f,");
        sb.AppendLine($"            (TextAnchor){raw.ChildAlignment},");
        sb.AppendLine($"            {raw.PaddingLeft},");
        sb.AppendLine($"            {raw.PaddingRight},");
        sb.AppendLine($"            {raw.PaddingTop},");
        sb.AppendLine($"            {raw.PaddingBottom},");
        sb.AppendLine($"            {Bool(raw.ChildControlWidth)},");
        sb.AppendLine($"            {Bool(raw.ChildControlHeight)},");
        sb.AppendLine($"            {Bool(raw.ChildForceExpandWidth)},");
        sb.AppendLine($"            {Bool(raw.ChildForceExpandHeight)},");
        sb.AppendLine($"            sliderColorBlock,");
        sb.AppendLine($"            (Selectable.Transition){raw.SliderTransition},");
        sb.AppendLine($"            (Slider.Direction){raw.Direction},");
        sb.AppendLine($"            {Bool(raw.WholeNumbers)},");
        sb.AppendLine($"            {Float(raw.MinValue)}f,");
        sb.AppendLine($"            {Float(raw.MaxValue)}f)");
        sb.AppendLine("        {");
        sb.AppendLine($"            ClickSoundEventId = {raw.ClickSoundEventId}u");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    private static string ColorBlockLiteral(ExtractedColorBlock cb) =>
        $"new ColorBlock {{ normalColor = {ColorLiteral(cb.NormalColor)}, highlightedColor = {ColorLiteral(cb.HighlightedColor)}, pressedColor = {ColorLiteral(cb.PressedColor)}, disabledColor = {ColorLiteral(cb.DisabledColor)}, colorMultiplier = {Float(cb.ColorMultiplier)}f, fadeDuration = {Float(cb.FadeDuration)}f }}";

    private static string SwitchLayoutGroupLiteral(SwitchLayoutRawStyle layout) =>
        $"new SwitchLayoutGroup({Float(layout.Spacing)}f, (TextAnchor){layout.ChildAlignment}, {Bool(layout.ChildControlWidth)}, {Bool(layout.ChildControlHeight)}, {Bool(layout.ChildForceExpandWidth)}, {Bool(layout.ChildForceExpandHeight)}, {layout.PaddingLeft}, {layout.PaddingRight}, {layout.PaddingTop}, {layout.PaddingBottom})";

    private static string ColorLiteral(Color color) =>
        $"new Color({Float(color.R)}f, {Float(color.G)}f, {Float(color.B)}f, {Float(color.A)}f)";

    private static string RectDataLiteral(RectData rect) =>
        $"new RectData(new Vector2({Float(rect.AnchorMinX)}f, {Float(rect.AnchorMinY)}f), new Vector2({Float(rect.AnchorMaxX)}f, {Float(rect.AnchorMaxY)}f), new Vector2({Float(rect.SizeDeltaX)}f, {Float(rect.SizeDeltaY)}f), new Vector2({Float(rect.AnchoredPositionX)}f, {Float(rect.AnchoredPositionY)}f), new Vector2({Float(rect.PivotX)}f, {Float(rect.PivotY)}f))";

    private static string TextAppearanceLiteral(ExtractedTextAppearance text) =>
        $"new TextAppearance(TMP_FontAssetResolver.Resolve({StringLiteral(text.FontAssetName)}), MaterialResolver.Resolve({StringLiteral(text.MaterialName)}), {Float(text.FontSize)}f, {ColorLiteral(text.Color)}, (TextAlignmentOptions){text.Alignment}, (FontStyles){text.FontStyle}, {Float(text.OutlineWidth)}f, {Bool(text.EnableWordWrapping)}, {Bool(text.EnableAutoSizing)}, (TextOverflowModes){text.OverflowMode}, {Float(text.FontSizeMin)}f, {Float(text.FontSizeMax)}f)";

    private static string StringLiteral(string? value) =>
        value is null ? "null" : $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Float(float value) =>
        value.ToString(CultureInfo.InvariantCulture);
}
