<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>EmberConfig.ExampleMod</AssemblyName>
    <RootNamespace>EmberConfig.ExampleMod</RootNamespace>
    <Product>EmberConfig Example</Product>
    <Version>1.0.0</Version>
    <BepInExPluginGuid>zeprus.gunfire.EmberConfig.ExampleMod</BepInExPluginGuid>
    <BepInExPluginName>EmberConfig Example</BepInExPluginName>
    <BepInExPluginVersion>1.0.0</BepInExPluginVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
    <DeployToPlugins>false</DeployToPlugins>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmberConfig\EmberConfig.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(GameLibDir)\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameLibDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GameLibDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="Deploy" AfterTargets="Build;Publish" Condition="'$(DeployToPlugins)' != 'false'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExDir)\plugins" />
  </Target>

</Project>
